	</div>
	<div class="theme_mod_selector"></div>
</div><!-- /.theme_outline -->

<div class="theme_footer">
	<p class="center">This app works on <a href="https://github.com/tomk79/PxFW-1.x" onclick="air.navigateToURL(new air.URLRequest(this.href));return false;">Pickles Framework</a>.</p>
	<p class="center"><a href="app:/index.html" onclick="air.NativeApplication.nativeApplication.exit(); return false;">このアプリケーションを終了する</a></p>
</div><!-- /.theme_footer -->
